on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ${{ secrets.FTP_PROTOCOL }}
          local-dir: ./
          server-dir: /doxa_nextjs/

      - name: Create SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_DOXA_PLC_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash

      - name: Configuration to cPanel
        run: |
          ssh -i ../private.key doxapldm@91.204.209.38 
          source /home/doxapldm/nodevenv/doxa_nextjs/20/bin/activate && cd /home/doxapldm/doxa_nextjs 
          npm install
          npm run build
